# Generated by Django 4.1.2 on 2022-10-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, null=True)),
                ('option_one', models.CharField(max_length=200, null=True)),
                ('option_two', models.CharField(max_length=200, null=True)),
                ('option_three', models.CharField(max_length=200, null=True)),
                ('option_four', models.CharField(max_length=200, null=True)),
                ('answer', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
